//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealOnlineBillingNew.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ItemMaster
    {
        public long itemId { get; set; }
        public string ItemName { get; set; }
        public Nullable<long> itemTypeId { get; set; }
        public Nullable<long> unitId { get; set; }
        public Nullable<long> taxId { get; set; }
        public Nullable<decimal> SalesRate { get; set; }
        public Nullable<decimal> MrpRate { get; set; }
        public Nullable<decimal> productDisc { get; set; }
        public Nullable<decimal> createdDate { get; set; }
        public Nullable<decimal> updatedDate { get; set; }
        public Nullable<decimal> reOrderQty { get; set; }
        public Nullable<decimal> MaxQty { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
