//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealOnlineBillingNew.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Tax
    {
        public long taxId { get; set; }
        public string taxName { get; set; }
        public Nullable<decimal> rate { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<decimal> createdDate { get; set; }
        public Nullable<decimal> updatedDate { get; set; }
    }
}
