//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealOnlineBillingNew.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCategoryMaster
    {
        public long categoryId { get; set; }
        public string categoryName { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
