//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealOnlineBillingNew.Context
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class tblFirmDetail
    {
        public long firmId { get; set; }
        public string firmName { get; set; }
        public string firmAddress { get; set; }
        public string firmcontact { get; set; }
        public string gstNo { get; set; }
        public string subjectTo { get; set; }
        public string firmFor { get; set; }
        public string Services { get; set; }
        public string bankName { get; set; }
        public string acNo { get; set; }
        public string branchname { get; set; }
        public string ifscCode { get; set; }
        public string logoPath { get; set; }
        public byte[] logoBinary { get; set; }
        public string firmType { get; set; }
        public string cmpId { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }

        public HttpPostedFileWrapper ImageFile { get; set; }
        // public HttpPostedFileWrapper ImageFile { get; set; }

    }
}
