//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdealOnlineBillingNew.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductMaster
    {
        public long productId { get; set; }
        public string productName { get; set; }
        public Nullable<long> productTypeId { get; set; }
        public Nullable<long> prodCmpId { get; set; }
        public Nullable<long> unitId { get; set; }
        public Nullable<long> taxId { get; set; }
        public string hsn { get; set; }
        public Nullable<decimal> reOrderQty { get; set; }
        public Nullable<decimal> MaxQty { get; set; }
        public Nullable<long> firmId { get; set; }
        public string barcode { get; set; }
        public string barcodeImgPath { get; set; }
        public byte[] barcodeImgBytes { get; set; }
        public byte[] barcoodeImageName { get; set; }
        public Nullable<System.DateTime> updatedDate { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
